name: "Yarn 2 Bump Action"

description: Bumping version of specified dependencies for Yarn 2 PnP.

branding:
  icon: package
  color: blue

inputs:
  pattern:
    description: Pattern of dependency name
    required: true
    default: "*"

  exclude:
    description: Pattern of dependency name to exclude
    required: false

  branch:
    description: Name of branch that the bumping result is synced
    required: true

  repository:
    description: GitHub repository
    required: true
    default: ${{ github.repository }}

  username:
    description: Git username
    required: true
    default: "GitHub Action"

  email:
    description: Git email
    required: true
    default: "action@github.com"

  commit-message:
    description: Git commit message text
    required: true
    default: "Bump-up dependencies"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_REPOSITORY: ${{ inputs.repository }}
    GIT_USERNAME: ${{ inputs.username }}
    GIT_EMAIL: ${{ inputs.email }}
    GIT_BRANCH: ${{ inputs.branch }}
    GIT_COMMIT_MSG: ${{ inputs.commit-message }}
  args:
    - "${{ inputs.pattern }}"
    - --exclude "${{ inputs.exclude }}"
